// Enforces Conventional Commits (https://www.conventionalcommits.org/) on every commit in a PR.
// Standard types only (feat, fix, docs, chore, ci, test, refactor, build, ...) - no custom
// type-enum, so this stays generic across whatever content this template is used for. Scope is
// optional and free-form; see CONTRIBUTING.md for the scopes this repo's own convention suggests.
module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [
    // git subtree's own auto-generated commit messages (from `git subtree add/pull --squash` on
    // .tad/) don't follow Conventional Commits and never will - they're generated by `git subtree`
    // itself, not written by a person, and this recurs on every future engine update, not just
    // once. commitlint's built-in defaults already skip git's own "Merge branch ..." / "Merge pull
    // request ..." messages; these two are git subtree's equivalent, which aren't covered by that.
    (commit) => /^Squashed '/.test(commit),
    (commit) => /^Merge commit '/.test(commit),
  ],
  rules: {
    // Dependabot's own commits ("Bump X from Y to Z", a release-notes body with long lines) are
    // valid Conventional Commits (type build/chore + scope) but fail these two default style
    // rules. Relaxed so Dependabot's own PRs pass; everything else from config-conventional
    // (type-enum, header format, blank line between header/body, ...) still applies.
    "subject-case": [0],
    "body-max-line-length": [0],
  },
};
